
spring.application.name=manager_music
spring.web.resources.static-locations=classpath:/static/,file:///D:/Data/C1025L1-JV105/backend/module_4/ss04_spring_mvc_data_binding/bai_tap/manager_music/src/main/resources/static/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
